DonateCRW/DonateCRW/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    # Paths del core
    path('', include('core.urls')),
    # Paths of projects
    path('projects/', include('services.urls')),
    # Paths de pages
    path('page/', include('pages.urls')),
    # Paths de blog
    path('blog/', include('blog.urls')),
    # Paths de contact
    path('contact/', include('contact.urls')),
    # Paths del admin
    path('daocrown/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DonateCRW/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    #Paths del core
    path("", views.blog, name = "blog"),
    #path('category/<int:category_id>/', views.category, name="category"),
]

DonateCRW/services/urls.py
from django.urls import path
from . import views
from .views import ServiceDetailView, ServiceListView, ServiceCompletedListView

urlpatterns = [
    #path('', views.services, name="services"),
    path('', ServiceListView.as_view(), name='services'),
    path('completed/', ServiceCompletedListView.as_view(), name='completed'),
    path('category/<int:category_id>/', views.category, name = "category"),
    path('<int:pk>/', ServiceDetailView.as_view(), name='service'),
]

DonateCRW/services/models.py
from django.db import models
from django.utils.timezone import now
from ckeditor.fields import RichTextField

#TESSTTTT SLUGIFY
from django.template import defaultfilters


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name="Name")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Date of created")
    updated = models.DateTimeField(auto_now=True, verbose_name="Date of edition")

    class Meta:
        verbose_name = "category"
        verbose_name_plural = "categories"
        ordering = ['-created']

    def __str__(self):
        return self.name


class Service(models.Model):

    title = models.CharField(max_length=200, verbose_name="Title")
    subtitle = models.CharField(max_length=200, verbose_name="Subtitle")
    published = models.DateTimeField(verbose_name="Published", default=now)
    finish = models.DateTimeField(verbose_name="Finish", default=now)
    wallet_shop = models.CharField(max_length=100, verbose_name="Address Shop")
    crw_donate = models.IntegerField(verbose_name="Crown needed")
    wallet_donate = models.CharField(null=True, blank=True, max_length=100, verbose_name="Address for donate ")
    amount_donate = models.CharField(null=True, blank=True, max_length=18, verbose_name="Amount donate")
    amount_needed = models.CharField(null=True, blank=True, max_length=18, verbose_name="Amount needed")
    content = RichTextField(verbose_name="Description")
    image = models.ImageField(verbose_name="Image", upload_to="services")
    categories = models.ManyToManyField(Category, verbose_name="Categories", related_name="get_projects")
    progress = models.CharField(null=True, blank=True, max_length=5, verbose_name="Progress")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Date of created")
    updated = models.DateTimeField(auto_now=True, verbose_name="Date of edition")
    completed = models.BooleanField(default=False, verbose_name="Completed")

    class Meta:
        verbose_name = "project"
        verbose_name_plural = "projects"
        ordering = ['-created']

    def __str__(self):
        return self.title


    #TESSTTTT SLUGIFY
    def save(self, *args, **kwargs):
      self.slug = defaultfilters.slugify(self.title)
      super(Service, self).save(*args, **kwargs)

DonateCRW/services/views.py
from django.shortcuts import render, get_object_or_404
from .models import Service, Category
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView


def category(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    return render (request, "services/category.html", {'category':category})


class ServiceListView(ListView):
    model = Service


class ServiceCompletedListView(ListView):
    model = Service

    template_name = 'services/completed_list.html'

class ServiceDetailView(DetailView):
    model = Service

DonateCRW/services/templates/services/category.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Servicios{% endblock %}

{% load qr_code %}

{% block content %}
  {% for service in category.get_projects.all%}
  
    <section class="page-section">
      <div class="container">
        <div class="product-item">
          <div class="product-item-title d-flex">
            <div class="bg-faded p-5 d-flex mr-auto rounded">
              <h2 class="section-heading mb-0">
                <span class="section-heading-upper">{{service.subtitle}}</span>
                <span class="section-heading-lower">{{service.title}}</span>
              </h2>
            </div>
          </div>
          <img class="product-item-img mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{{service.image.url}}" alt="">
          <div class="product-item-description d-flex ml-auto">
            <div class="bg-faded p-5 rounded">
              <p class="mb-0">{{service.content|safe}}</p>
              <span class="section-heading-lower">Address Project: <b>{{service.wallet_donate}}</b></span>
              <br>
              <span class="section-heading-lower">Crowns donated: <b>{{service.amount_donate}} CRW </b></span>
              <br>
              <span class="section-heading-lower">They are still need <b>{{service.amount_needed}} CRW</b> to complete the project.</span>
              <br>
              <span class="section-heading-lower">Category: <b>
                {% for category in service.categories.all %}
                  <a href="{% url 'category' category.id %}" class="link">{{category.name}}</a>{% if not forloop.last %},{% endif %}
                {% endfor %}
              </b></span>
              <br>
              <span class="section-heading-lower">Published: <b>{{service.published|date:"SHORT_DATE_FORMAT"}}</b></span>
              <br>
              <span class="section-heading-upper">{% qr_from_text service.wallet_donate size="S" %} </span>
            </div>
          </div>
        </div>
      </div>
    </section>
   
  {% endfor %}
{% endblock %}

DonateCRW/services/templates/services/completed_list.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Projects{% endblock %}

{% load qr_code %}

{% block content %}
<div class="container-fluid">
  <div class="container">
    <div class="row">
        {% for service in service_list %}
        {% if service.completed == True %}
        <div class="col-md-6">
          <div class="card mt-4 mb-4 box-shadow">
            <img class="card-img-top" src="{{service.image.url}}" alt="Card image cap">
            <div class="card-body">
              <p class="card-text"><b>{{service.subtitle}}</b></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="section-heading-upper">
                  <h6><b>Goal: </b><span class="badge badge-primary">{{service.crw_donate}} CRW</span></h6>
                </div>
                <div class="section-heading-upper">
                    <h6><b>Donated: </b><span class="badge badge-primary">{{service.amount_donate}} CRW</span></h6>
                </div>
                <div class="section-heading-upper">
                    <h6><b>COMPLETED!! Thanks at all!!</b></span></h6>
                </div>
                  <span >{% qr_from_text service.wallet_donate size="T" %} </span>  
              </div>
              <p><b>Progress: </b></p>
              <div class="progress">
                  <div class="progress-bar" role="progressbar" aria-valuenow="70"
                  aria-valuemin="0" aria-valuemax="100" style="width:{{service.progress}}">
                    {{service.progress}}
                  </div>
              </div>
              <br>
                <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'service' service.id %}" class="btn btn-primary" role="button">See project</a>
                </div>
                <small class="text-muted">Finish:{{service.finish|date:"SHORT_DATE_FORMAT"}}</small>
              </div>
            </div>
          </div>
        </div>
      {% endif %}
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

DonateCRW/services/templates/services/service_detail.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Servicios{% endblock %}

{% load qr_code %}

{% block content %}
    <section class="page-section">
      <div class="container">
        <div class="product-item">
          <div class="product-item-title d-flex">
            <div class="bg-faded p-5 d-flex mr-auto rounded">
              <h2 class="section-heading mb-0">
                <span class="section-heading-upper">{{service.subtitle}}</span>
                <span class="section-heading-lower">{{service.title}}</span>
              </h2>
            </div>
          </div>
          <img class="product-item-img mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{{service.image.url}}" alt="">
          <div class="product-item-description d-flex ml-auto">
            <div class="bg-faded p-5 rounded">
              <p class="mb-0">{{service.content|safe}}</p>
              <span class="section-heading-lower">Address Project: <a href="https://chainz.cryptoid.info/crw/address.dws?{{service.wallet_donate}}" target=_blank class="link">{{service.wallet_donate}}</a></span>
              <br>
              <span class="section-heading-lower">Crowns Donated: <b>{{service.amount_donate}} CRW </b></span>
              <br>
              <span class="section-heading-lower">Crowns Needed: <b>{{service.amount_needed}} CRW </b></span>
              <br>
              <span class="section-heading-lower">Category: <b>
                {% for category in service.categories.all %}
                  <a href="{% url 'category' category.id %}" class="link">{{category.name}}</a>{% if not forloop.last %},{% endif %}
                {% endfor %}
              <br>
              <p>Progress:</p>
              <div class="progress">
                  <div class="progress-bar" role="progressbar" aria-valuenow="70"
                  aria-valuemin="0" aria-valuemax="100" style="width:{{service.progress}}">
                  {{service.progress}}
                  </div>
              </div>
              </b>
              <span class="section-heading-upper">{% qr_from_text service.wallet_donate size="S" %} </span>
              <div class="btn-group">
                <a href="{% url 'services' %}" class="btn btn-primary" role="button">Return Projects</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

DonateCRW/services/templates/services/service_list.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Projects{% endblock %}

{% load qr_code %}

{% block content %}
<div class="container-fluid">
  <div class="container">
    <div class="row">
        {% for service in service_list %}
        {% if service.completed == False %}
        <div class="col-md-6">
          <div class="card mt-4 mb-4 box-shadow">
            <img class="card-img-top" src="{{service.image.url}}" alt="Card image cap">
            <div class="card-body">
              <p class="card-text"><b>{{service.subtitle}}</b></p>
              <!-- <p class="card-text">{{service.content|safe|truncatechars:"150"}}</p> -->
              <div class="d-flex justify-content-between align-items-center">
                <div class="section-heading-upper">
                  <h6><b>Goal: </b><span class="badge badge-primary">{{service.crw_donate}} CRW</span></h6>
                </div>
                <div class="section-heading-upper">
                    <h6><b>Donated: </b><span class="badge badge-primary">{{service.amount_donate}} CRW</span></h6>
                </div>
                <div class="section-heading-upper">
                    <h6><b>Needed: </b><span class="badge badge-primary">{{service.amount_needed}} CRW</span></h6>
                </div>
                  <span >{% qr_from_text service.wallet_donate size="T" %} </span>  
              </div>
              <p><b>Progress: </b></p>
              <div class="progress">
                  <div class="progress-bar" role="progressbar" aria-valuenow="70"
                  aria-valuemin="0" aria-valuemax="100" style="width:{{service.progress}}">
                    {{service.progress}}
                  </div>
              </div>
              <br>
                <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'service' service.id %}" class="btn btn-primary" role="button">See project</a>
                </div>
                <small class="text-muted">Finish:{{service.finish|date:"SHORT_DATE_FORMAT"}}</small>
              </div>
            </div>
          </div>
        </div>
      {% endif %}
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

DonateCRW/services/templates/services/services.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Servicios{% endblock %}

{% load qr_code %}

{% block content %}
  {% for service in services reversed %}
    <section class="page-section">
      <div class="container">
        <div class="product-item">
          <div class="product-item-title d-flex">
            <div class="bg-faded p-5 d-flex mr-auto rounded">
              <h2 class="section-heading mb-0">
                <span class="section-heading-upper">{{service.subtitle}}</span>
                <span class="section-heading-lower">{{service.title}}</span>
              </h2>
            </div>
          </div>
          <img class="product-item-img mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{{service.image.url}}" alt="">
          <div class="product-item-description d-flex ml-auto">
            <div class="bg-faded p-5 rounded">
              <p class="mb-0">{{service.content}}</p>
              <span class="section-heading-lower">Wallet para donar: <b>{{service.wallet_donate}}</b></span>
              <br>
              <span class="section-heading-lower">Crowns donados: <b>{{service.amount_donate}} CRW </b></span>
              <br>
              <span class="section-heading-lower">Todavia son necesarios <b>{{service.amount_needed}} CRW</b> para completar el proyecto.</span><br>
              <span class="section-heading-upper">{% qr_from_text service.wallet_donate size="S" %} </span>
            </div>
          </div>
        </div>
      </div>
    </section>
  {% endfor %}
{% endblock %}